## GET flight-service default configurations
GET localhost:6464/flight-service/default

###

## GET flight-service development environment configurations
GET localhost:6464/flight-service/dev

###

## GET flight-service development environment configurations
GET localhost:6464/flight-service/prod